---
name: BEAM Docker Release
description: Publish BEAM release as a Docker image
inputs:
  registry:
    description: Container Registry
    required: true
  username:
    description: Registry Username
    required: true
  password:
    description: Registry Password
    required: true
runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: checkout
      uses: actions/checkout@v3
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: ERTS System Infomation
      run: $GITHUB_ACTION_PATH/bin/system
      id: system
      shell: bash
    - name: Release Information
      run: $GITHUB_ACTION_PATH/bin/release
      id: release
      shell: bash
    - name: Copy BEAM Release Action Scripts
      run: cp -r $GITHUB_ACTION_PATH/bin beam-docker-release-action
    - name: Substitute Dockerfile M4 variables
      run: >
        m4
        -DERTS_VSN=${{ steps.system.outputs.version }}
        -DREL_NAME=${{ steps.release.outputs.name }}
        -DREL_VSN=${{ steps.release.outputs.version }}
        $GITHUB_ACTION_PATH/Dockerfile.m4 >Dockerfile
      shell: bash
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          OTP_VERSION=${{ steps.system.outputs.otp }}
        build-args: |
          GITHUB_REPOSITORY=${{ github.repository }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.username }}/${{ steps.release.outputs.name }}
