# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
runs:
  using: "composite"
  steps:
    - name: ERTS System Infomation
      run: $GITHUB_ACTION_PATH/bin/system
      id: system
      shell: bash
    - name: Release Information
      run: $GITHUB_ACTION_PATH/bin/release
      id: release
      shell: bash
    - name: Application Information
      run: $GITHUB_ACTION_PATH/bin/app
      id: app
      shell: bash
    - name: Copy Release Runtime Dependencies
      run: $GITHUB_ACTION_PATH/bin/mkimage ${{ steps.release.outputs.name }}
      shell: bash
    - name: Substitute Dockerfile M4 variables
      run: >
        m4
        -DETS_VSN=${{ steps.system.outputs.version }}
        -DREL_NAME=${{ steps.release.outputs.name }}
        -DREL_VSN=${{ steps.release.outputs.version }}
        $GITHUB_ACTION_PATH/Dockerfile.m4 >Dockerfile
      shell: bash
    - name: Docker Build
      run: >
        docker build
        --pull=true
        --no-cache=true
        --force-rm=true
        -t
        ${{ env.REGISTRY }}/${{ github.actor }}/${{ steps.release.outputs.name }}:${{ steps.app.outputs.version }}
        .
      shell: bash
    - name: Docker Push
      run: >
        docker
        push
        ${{ env.REGISTRY }}/${{ github.actor }}/${{ steps.release.outputs.name }}:${{ steps.app.outputs.version }}
      shell: bash
