---
name: BEAM Docker Release
description: Publish BEAM release as a Docker image
inputs:
  registry:
    description: Container Registry
    required: true
  username:
    description: Registry Username
    required: true
  password:
    description: Registry Password
    required: true
  build-image:
    description: Build image
    default: erlang:25.1.1.0
  build-command:
    description: Build command
    default: make
  build-platforms:
    description: Build platforms
    default: linux/amd64,linux/arm/v7
  build-tag:
    description: Build tag
    default: ${{ github.repository }}
  build-push:
    description: Build push image
    default: true
runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Copy BEAM Release Action Dockerfile
      run: cp -r $GITHUB_ACTION_PATH/Dockerfile .
      shell: bash
    - name: Copy BEAM Release Action Scripts
      run: cp -r $GITHUB_ACTION_PATH/bin beam-docker-release-action
      shell: bash
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: ${{inputs.build-platforms}}
        build-args: |
          BUILD_IMAGE=${{inputs.build-image}}
          GITHUB_REPOSITORY=${{ github.repository }}
          BUILD_COMMAND=${{ inputs.build-command }}
        push: ${{ inputs.build-push }}
        tags: ${{ inputs.registry }}/${{ inputs.build-tag }}
