---
name: BEAM Docker Release
description: Publish BEAM release as a Docker image
inputs:
  registry:
    description: Container Registry
    required: true
  username:
    description: Registry Username
    required: true
  password:
    description: Registry Password
    required: true
runs:
  using: composite
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: ERTS System Infomation
      run: $GITHUB_ACTION_PATH/bin/system
      id: system
      shell: bash
    - name: Release Information
      run: $GITHUB_ACTION_PATH/bin/release
      id: release
      shell: bash
    - name: Application Information
      run: $GITHUB_ACTION_PATH/bin/app
      id: app
      shell: bash
    - name: Copy Release Runtime Dependencies
      run: $GITHUB_ACTION_PATH/bin/mkimage ${{ steps.release.outputs.name }}
      shell: bash
    - name: Substitute Dockerfile M4 variables
      run: >
        m4
        -DERTS_VSN=${{ steps.system.outputs.version }}
        -DREL_NAME=${{ steps.release.outputs.name }}
        -DREL_VSN=${{ steps.release.outputs.version }}
        $GITHUB_ACTION_PATH/Dockerfile.m4 >Dockerfile
      shell: bash
    - name: Docker Build
      run: >
        docker build
        --pull=true
        --no-cache=true
        --force-rm=true
        -t
        ${{ inputs.registry }}/${{ inputs.username }}/${{ steps.release.outputs.name }}:${{ steps.app.outputs.version }}
        .
      shell: bash
    - name: Docker Push
      run: >
        docker
        push
        ${{ inputs.registry }}/${{ inputs.username }}/${{ steps.release.outputs.name }}:${{ steps.app.outputs.version }}
      shell: bash
